cp evaluation.py eval1.py
cp evaluation.py eval2.py
cp evaluation.py eval3.py
cp evaluation.py eval4.py
cp evaluation.py eval5.py
cp evaluation.py eval6.py
cp evaluation.py eval7.py
cp evaluation.py eval8.py
cp evaluation.py eval9.py
